CREATE EXTENSION IF NOT EXISTS timescaledb;

CREATE TABLE "users"(
    "user_id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "user_email" VARCHAR(255) NOT NULL,
    "user_password_hash" VARCHAR(255) NOT NULL,
    "user_role" VARCHAR(255) CHECK (
        "user_role" IN (
            'guest',
            'operator',
            'supervisor',
            'administrator',
            'platformAdmin'
        )
    ) NOT NULL DEFAULT 'guest',
    "user_nickname" VARCHAR(255) NOT NULL,
    "user_created_at" TIMESTAMP(0) WITH TIME ZONE NOT NULL,
    "user_registered_at" TIMESTAMP(0) WITH TIME ZONE NOT NULL,
    "user_updated_at" TIMESTAMP(0) WITH TIME ZONE NOT NULL,
    PRIMARY KEY("user_id"),
    CONSTRAINT "users_user_email_unique" UNIQUE("user_email")
);

CREATE TABLE "gateways"(
    "gateway_id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "gateway_token_hash" VARCHAR(255) NOT NULL,
    "gateway_description" TEXT NOT NULL,
    "gateway_name" VARCHAR(255) NOT NULL,
    "gateway_location" VARCHAR(255) NOT NULL,
    "gateway_latitude" DECIMAL(9, 6) NOT NULL,
    "gateway_longitude" DECIMAL(9, 6) NOT NULL,
    PRIMARY KEY("gateway_id"),

    CONSTRAINT "gateways_gateway_token_hash_unique" UNIQUE("gateway_token_hash"),

    CONSTRAINT "gateways_latitude_check"
        CHECK ("gateway_latitude" >= -90 AND "gateway_latitude" <= 90),

    CONSTRAINT "gateways_longitude_check"
        CHECK ("gateway_longitude" >= -180 AND "gateway_longitude" <= 180)
);

CREATE TABLE "telemetries"(
    "telemetry_id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "telemetry_remote_id" BIGINT NOT NULL,
    "telemetry_gateway_id" BIGINT NOT NULL,
    "telemetry_measured_at_utc" TIMESTAMP(0) WITH TIME ZONE NOT NULL,
    "telemetry_received_at_utc" TIMESTAMP(0) WITH TIME ZONE NOT NULL,
    "telemetry_temperature" DOUBLE PRECISION NOT NULL,
    "telemetry_pressure" DOUBLE PRECISION NOT NULL,
    "telemetry_humidity" DOUBLE PRECISION NOT NULL,
    "telemetry_lighting" DOUBLE PRECISION NOT NULL,
    "telemetry_raindrops_amount" BIGINT NOT NULL,
    "telemetry_node_battery_level" SMALLINT,
    "telemetry_node_wifi_strength" SMALLINT,

    PRIMARY KEY("telemetry_id", "telemetry_measured_at_utc"),

    CONSTRAINT "telemetries_gateway_measured_at_unique"
        UNIQUE("telemetry_gateway_id", "telemetry_measured_at_utc"),

    CONSTRAINT "telemetries_humidity_check"
        CHECK ("telemetry_humidity" >= 0 AND "telemetry_humidity" <= 100),

    CONSTRAINT "telemetries_lighting_check"
        CHECK ("telemetry_lighting" >= 0),

    CONSTRAINT "telemetries_raindrops_amount_check"
        CHECK ("telemetry_raindrops_amount" >= 0),

    CONSTRAINT "telemetries_node_battery_level_check"
        CHECK (
            "telemetry_node_battery_level" IS NULL
            OR (
                "telemetry_node_battery_level" >= 0
                AND "telemetry_node_battery_level" <= 100
            )
        )
);

SELECT create_hypertable(
    'telemetries',
    by_range('telemetry_measured_at_utc'),
    if_not_exists => TRUE
);

COMMENT ON TABLE "telemetries" IS 'Timescale hypertable for gateway telemetry measurements.';

CREATE TABLE "notifications"(
    "notification_id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "notification_is_for_admins_only" BOOLEAN NOT NULL,
    "notification_text" TEXT NOT NULL,
    "notification_type" VARCHAR(255) CHECK (
        "notification_type" IN ('warning', 'info', 'danger')
    ) NOT NULL,
    "notification_gateway_id" BIGINT NULL,
    PRIMARY KEY("notification_id")
);

CREATE TABLE "user_sessions"(
    "session_id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "session_user_id" BIGINT NOT NULL,
    "session_token_hash" VARCHAR(255) NOT NULL,
    "session_token_rotated_at" TIMESTAMP(0) WITH TIME ZONE NOT NULL,
    "session_expires_at" TIMESTAMP(0) WITH TIME ZONE NOT NULL,
    "session_created_at" TIMESTAMP(0) WITH TIME ZONE NOT NULL,
    "session_revoked_at" TIMESTAMP(0) WITH TIME ZONE NULL,
    PRIMARY KEY("session_id"),
    CONSTRAINT "user_sessions_session_token_hash_unique" UNIQUE("session_token_hash")
);

CREATE TABLE "invites"(
    "invite_id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "invite_email" VARCHAR(255) NOT NULL,
    "invite_token_hash" VARCHAR(255) NOT NULL,
    "invite_invited_by" BIGINT NOT NULL,
    "invite_expires_at" TIMESTAMP(0) WITH TIME ZONE NOT NULL,
    "invite_fulfilled_at" TIMESTAMP(0) WITH TIME ZONE NULL,
    PRIMARY KEY("invite_id"),
    CONSTRAINT "invites_invite_token_hash_unique" UNIQUE("invite_token_hash")
);

CREATE TABLE "users_notifications"(
    "notification_id" BIGINT NOT NULL,
    "user_id" BIGINT NOT NULL,
    "acknowledged" BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY("notification_id", "user_id")
);

ALTER TABLE
    "telemetries"
    ADD CONSTRAINT "telemetries_telemetry_gateway_id_foreign"
    FOREIGN KEY("telemetry_gateway_id")
    REFERENCES "gateways"("gateway_id")
    ON DELETE CASCADE;

ALTER TABLE
    "notifications"
    ADD CONSTRAINT "notifications_notification_gateway_id_foreign"
    FOREIGN KEY("notification_gateway_id")
    REFERENCES "gateways"("gateway_id")
    ON DELETE SET NULL;

ALTER TABLE
    "user_sessions"
    ADD CONSTRAINT "user_sessions_session_user_id_foreign"
    FOREIGN KEY("session_user_id")
    REFERENCES "users"("user_id")
    ON DELETE CASCADE;

ALTER TABLE
    "invites"
    ADD CONSTRAINT "invites_invite_invited_by_foreign"
    FOREIGN KEY("invite_invited_by")
    REFERENCES "users"("user_id")
    ON DELETE CASCADE;

ALTER TABLE
    "users_notifications"
    ADD CONSTRAINT "users_notifications_notification_id_foreign"
    FOREIGN KEY("notification_id")
    REFERENCES "notifications"("notification_id")
    ON DELETE CASCADE;

ALTER TABLE
    "users_notifications"
    ADD CONSTRAINT "users_notifications_user_id_foreign"
    FOREIGN KEY("user_id")
    REFERENCES "users"("user_id")
    ON DELETE CASCADE;

CREATE INDEX "telemetries_gateway_measured_at_index"
    ON "telemetries"("telemetry_gateway_id", "telemetry_measured_at_utc" DESC);

CREATE INDEX "user_sessions_user_id_index"
    ON "user_sessions"("session_user_id");

CREATE INDEX "invites_invited_by_index"
    ON "invites"("invite_invited_by");

CREATE INDEX "notifications_gateway_id_index"
    ON "notifications"("notification_gateway_id");

CREATE INDEX "invites_email_index"
    ON "invites"("invite_email");